typography_spectrum: 0.4789840520825237
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5206007643137127
  lightness: 0.43045935314148664
  saturation: 0.30694293789565563
  rhythmicContrast: 0.7844775426201522
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6702489159069955
analytics:
  google: null
  facebook: null
  twitter: null
name: ModernPics
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ModernPics Photography
description: Hello World
purpose: []
